#Note, in the build dir you need the server binary for your environment, you can get it from the server_setup.sh script
FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    libgomp1 \
    openssh-server \
    sudo \
    curl \
    unzip \
    wget \
    vim \
    nvtop \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

RUN mkdir -p /run/sshd

WORKDIR /app/backend
RUN pip install -r requirements.txt

WORKDIR /app/frontend
COPY frontend /app/frontend
RUN npm install
RUN npm run build

WORKDIR /app
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
