# ==================
# Base Image
# ==================
FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04 AS base

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    libgomp1 \
    openssh-server \
    sudo \
    curl \
    unzip \
    wget \
    vim \
    nvtop \
    python3 \
    python3-pip \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt /app/backend/requirements.txt
WORKDIR /app/backend
RUN pip install -r requirements.txt

WORKDIR /app/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install


# ==================
# Application
# ==================
FROM base AS final

WORKDIR /app

COPY backend /app/backend
COPY frontend /app/frontend
COPY entrypoint.sh /entrypoint.sh
COPY setup.sh /app/setup.sh

RUN chmod +x /entrypoint.sh /app/setup.sh

WORKDIR /app/frontend
RUN npm run build

ENTRYPOINT ["/entrypoint.sh"]
