FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    libgomp1 \
    openssh-server \
    sudo \
    curl \
    unzip \
    wget \
    vim \
    nvtop \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

RUN mkdir server && \
    unzip /app/undreamai-v1.1.10-llamacpp.zip -d /app/server/ && \
    unzip /app/undreamai-v1.1.10-server.zip -d /app/server/ && \
    unzip /app/undreamai-v1.1.10-llamacpp-full.zip -d /app/server/

RUN mkdir -p /models

WORKDIR /app/backend
RUN pip install -r requirements.txt

WORKDIR /app/frontend
COPY frontend /app/frontend
RUN npm install
RUN npm run build

WORKDIR /app
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
