FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    libgomp1 \
    openssh-server \
    sudo \
    curl \
    unzip \
    wget \
    vim \
    nvtop \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/sshd

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN mkdir /models

ENTRYPOINT ["/entrypoint.sh"]
