version: '3.9'

services:
  undreamai_server:
    build:
      context: ..
      dockerfile: shared/Dockerfile.local
    image: teocholakov/undreamai_server:v1.0.0
    container_name: undreamai_server
    network_mode: host
    ports:
      - "3000:3000"
      - "8000:8000"
      - "1337"
    volumes:
      - ./models:/models 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ALLOWLIST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped