version: '3.9'

services:
  undreamai_server:
    build:
      context: ..
      dockerfile: shared/Dockerfile.runpod
    image: teocholakov/undream_server:v1.1.0-runpod
    container_name: undreamai_server
    network_mode: host
    ports:
      - "3000:3000"
      - "8000:8000"
      - "22:22"
      - "1337"
    volumes:
      - ./models:/models 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CONTROL_PANEL_ALLOWLIST=${CONTROL_PANEL_ALLOWLIST:-0.0.0.0}
      - LLM_SERVER_ALLOWLIST=${LLM_SERVER_ALLOWLIST:-0.0.0.0}
      - ALLOWLIST=${ALLOWLIST:-0.0.0.0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped